<?xml version="1.0" encoding="UTF-8"?>
<!-- Tests compiled with Criterion v2.4.2 -->
<testsuites name="Criterion Tests" tests="32" failures="6" errors="0" disabled="0">
  <testsuite name="stress_suite" tests="1" failures="0" errors="0" disabled="0" skipped="0" time="18.453">
    <testcase name="stress_test" assertions="21" status="PASSED" time="18.453">
    </testcase>
  </testsuite>
  <testsuite name="pbx_suite" tests="2" failures="1" errors="0" disabled="0" skipped="0" time="25.012">
    <testcase name="many_threads_random_reg_unreg_premature" assertions="0" status="ERRORED" time="25.007">
      <error type="timeout" message="The test timed out." />    </testcase>
    <testcase name="dial_two_threads" assertions="1" status="PASSED" time="0.005">
    </testcase>
  </testsuite>
  <testsuite name="blackbox_suite" tests="17" failures="2" errors="0" disabled="0" skipped="0" time="17.646">
    <testcase name="pickup_hangup_test" assertions="2" status="PASSED" time="1.004">
    </testcase>
    <testcase name="pickup_hangup2_test" assertions="2" status="PASSED" time="1.007">
    </testcase>
    <testcase name="open_connection_valgrind_test" assertions="3" status="FAILED" time="1.208">
      <failure type="assert" message="1 assertion(s) failed."><![CDATA[tests/blackbox_tests.c:130: Valgrind reported errors]]>&#10;</failure>
    </testcase>
    <testcase name="open_connection_test" assertions="2" status="PASSED" time="1.004">
    </testcase>
    <testcase name="exercise_valgrind_test" assertions="3" status="PASSED" time="1.064">
    </testcase>
    <testcase name="exercise_test" assertions="2" status="PASSED" time="1.060">
    </testcase>
    <testcase name="dial_self_test" assertions="2" status="PASSED" time="1.004">
    </testcase>
    <testcase name="dial_good_test" assertions="2" status="PASSED" time="1.007">
    </testcase>
    <testcase name="dial_disconnect_test" assertions="2" status="PASSED" time="1.048">
    </testcase>
    <testcase name="dial_bad_test" assertions="2" status="PASSED" time="1.004">
    </testcase>
    <testcase name="dial_answer_test" assertions="2" status="PASSED" time="1.052">
    </testcase>
    <testcase name="connect_disconnect_valgrind_test" assertions="3" status="FAILED" time="1.142">
      <failure type="assert" message="1 assertion(s) failed."><![CDATA[tests/blackbox_tests.c:130: Valgrind reported errors]]>&#10;</failure>
    </testcase>
    <testcase name="connect_disconnect_test" assertions="2" status="PASSED" time="1.003">
    </testcase>
    <testcase name="connect_disconnect_many_valgrind_test" assertions="3" status="PASSED" time="1.015">
    </testcase>
    <testcase name="connect_disconnect_many_test" assertions="2" status="PASSED" time="1.014">
    </testcase>
    <testcase name="connect_disconnect2_valgrind_test" assertions="3" status="PASSED" time="1.004">
    </testcase>
    <testcase name="connect_disconnect2_test" assertions="2" status="PASSED" time="1.005">
    </testcase>
  </testsuite>
  <testsuite name="TU_suite" tests="12" failures="3" errors="0" disabled="0" skipped="0" time="0.049">
    <testcase name="tu_self_dial" assertions="4" status="PASSED" time="0.002">
    </testcase>
    <testcase name="tu_ref_stress" assertions="0" status="PASSED" time="0.022">
    </testcase>
    <testcase name="tu_pickup_repeat" assertions="1" status="FAILED" time="0.001">
      <failure type="assert" message="1 assertion(s) failed."><![CDATA[tests/__grading_helpers.c:47: tu_pickup second time, Failed to get expected value. Got: -1 | Expected: 0.]]>&#10;</failure>
    </testcase>
    <testcase name="tu_pickup_basic" assertions="3" status="PASSED" time="0.001">
    </testcase>
    <testcase name="tu_init" assertions="1" status="FAILED" time="0.001">
      <failure type="assert" message="1 assertion(s) failed."><![CDATA[tests/__grading_helpers.c:57: tu_init, Buffer is NULL.]]>&#10;</failure>
    </testcase>
    <testcase name="tu_fileno" assertions="1" status="FAILED" time="0.001">
      <failure type="assert" message="1 assertion(s) failed."><![CDATA[tests/__grading_helpers.c:47: tu_fileno, Failed to get expected value. Got: -1 | Expected: 9.]]>&#10;</failure>
    </testcase>
    <testcase name="tu_extension" assertions="1" status="PASSED" time="0.000">
    </testcase>
    <testcase name="tu_dial_off_hook" assertions="4" status="PASSED" time="0.001">
    </testcase>
    <testcase name="tu_dial_deadlock" assertions="0" status="PASSED" time="0.014">
    </testcase>
    <testcase name="tu_dial_basic" assertions="9" status="PASSED" time="0.001">
    </testcase>
    <testcase name="tu_chat_invalid" assertions="2" status="PASSED" time="0.001">
    </testcase>
    <testcase name="tu_chat_basic" assertions="9" status="PASSED" time="0.003">
    </testcase>
  </testsuite>
</testsuites>
